### ISSUE TITLE
Scrabble Discussion

### ISSUE THREAD

**Issue by jonpchin** [hashSort/Scrabble#2]
Hello team,

We will be making Scrabble(word game) in C# using Visual Studio. I currently have Visual Studio 2015 Community edition as its free. I recommend we all use the same version. The project will have a main goal of supporting player vs computer. We will eventually support multiplayer using a server but that is a long way off.

Game Details:

1. For the Scrabble board we have two options. Option one, our Scrabble game will have a 15x15 2D static array for backend to interact with the front end. Option two, we use object oriented style(using getter and setters) and have each Scrabble piece(an object) contain the score and letter.  We most likely will have to do both options to have more flexibility to do advanced things later on.

2.  We will use a wordList to help aide the computer make a good decision on what words he should try to go for. We will be using Edit distance algorithm for this. I have a good word list of about 150,000 words on my laptop I'll look for it and upload it to the repo.

3. We need a function to randomize the Scrabble letters and randomly select the player or computer to go first. This is usually done by someone picking a letter closest to A first for their first tile draw

4. Another function to randomly distribute to the player and computer the seven starting tiles. The  computers hand will not be shown obviously. 

5. Two levels of easy and hard. Easy will just randomly select tiles for the computer to place down while hard will use the edit algorithm.

6. The Scrabble game will have a total of 100 tiles and 2 of those tiles are blank which are wild tiles.

7. During a players turn, a player can do three options, place at least one tile on the board, exchange 1 or all of his tiles for new tiles, or pass.  The computer also has these three options. 

8. Tiles can only be placed horizontally or vertically, not diagonally. The words must read from left to right or top to bottom. 

9. The game is won when all 100 tiles are used and the player/computer with the highest score wins.
If any player/computers passes twice in a row the game will end and the person with the highest score wins.

Scoring:
Below are the point values for each letter that is used in a Scrabble game.

0 Points - Blank tile.

1 Point - A, E, I, L, N, O, R, S, T and U.

2 Points - D and G.

3 Points - B, C, M and P.

4 Points - F, H, V, W and Y.

5 Points - K.

8 Points - J and X.

10 Points - Q and Z.

Extra point values are awarded for multiple words and for placing tiles on the colored bonus point squares.

**Comment by jonpchin** [comment]
There are other rules and features  I have not mentioned for Scrabble. I'll add more later but this is a good list for now. Feel free to discuss the game implementations.

**Comment by richardwales2820** [comment]
Sounds like a great starting point and perfect plan to get this project rolling. I am using Visual Studio 2015 enterprise which is free from Microsoft with Dreamspark if you are interested! I'm not sure if the community edition has the Git plug-in, but I definitely would recommend it if it does not. Thanks for the write up! :)

**Comment by richardwales2820** [comment]
Here is the dreamspark link if you need it
https://e5.onthehub.com/WebStore/Welcome.aspx?vsro=8&ws=48858CBA-C19B-E011-969D-0030487D8897

**Comment by jonpchin** [comment]
Yeah I saw that site a few months ago with all the Visual Studio versions. At the time I only had Ubuntu so I didn't download it. I just checked the site and logged in and it says "Visual Studio Premium and Professional have been replaced by Visual Studio Community." It seems that they took the other versions down since the Community Edition is free. Its fine. I am sure the Community edition 2015 will work with other 2015 versions. I was just concerned if someone used a 2013 or later version of Visual Studios.

**Comment by richardwales2820** [comment]
Oh okay, awesome!

**Comment by jonpchin** [comment]
I just opened up the Solution you pushed to the repo so its community 2015 is compatible with your Enterprise 2015 version. I also noticed you have a word list. It looks like the same one I use. Are we going to use WPF for the GUI framework?

**Comment by richardwales2820** [comment]
I've been using Forms, but I don't know much about either one to make an educated decision, so if you want to jump ship to WPF that is definitely up to you!

**Comment by jonpchin** [comment]
WPF is newer and more flashy UI for faster computers but Winforms is more stable and been around for longer. The benefit of WPF is it has more flexibility in controlling the UI but at the cost of extra work. Both options are solid choices. Its important to get practice and exposure to both. So for this project since you said you been using WinForms we will stick to that. The next C# project we we will use WPF.

**Comment by richardwales2820** [comment]
Alright, sounds good to me!

**Comment by jonpchin** [comment]
I took a look at the code that you pushed. Are you using the drag and drop for the GUI designer? I have to resize the board layout as it went over my screen(your laptop screen may be taller/wider). Also the board tiles look uneven/crooked. I tried running the program. Just glancing over the code you seem to have most of the front end done and some of the back end. What are the remaining functions do we need to implement? I have a general idea of what to do next but I need to confirm as you pushed a lot of code in such a short period of time.

**Comment by jonpchin** [comment]
Nice. I like the dictionary idea for the wordList. The containsKey method is O(1).

**Comment by jonpchin** [comment]
I added some backend stuff for Scrabble. I'll work on some more of it tomorrow. We are using globals for some of the backend as I think its unnecessary to use getters and setters for all of it.

**Comment by jonpchin** [comment]
Okay here is what we are going to do. We are going to a 15x15 array of buttons for the Scrabble board. And for the players seven starting tiles we will also use Jbuttons. There will be three other buttons on the side of the board. Pass, Discard, End Turn. 

When a player clicks one of his own tiles he can either click a square on the Scrabble board and it will place that Tile on the board. Once a player has finished placing his tiles on the Scrabble board he can click End turn and then the words will be check to see if its correct, if not the tiles are removed from the board. After words the player gets his tiles refilled to seven. If a player clicks Pass button then it will switch to the computers turn. A player can also click 1-7 of his own tiles during his turn and press discard and then he will then get new tiles but his turn will end. 

The reason I would rather use Buttons instead of labels is because I know we can attach action listeners to the Buttons to register events. If you know how to use Labels to register action listeners then we can use labels.

**Comment by jonpchin** [comment]
Actually scratch the idea for the buttons. We can use labels as apparently we can attack action listeners to labels. That is good news so we won't need to refactor anything.
https://msdn.microsoft.com/en-us/library/dd553231.aspx

**Comment by richardwales2820** [comment]
Sweet man! I appreciate all of the explanations and advice for this. It's nice having someone experienced to guide me in the right direction and tell me why something is better over something else. Thanks!

**Comment by jonpchin** [comment]
You appear to be more experienced in .NET technologies then I am but I may have a little more experience in programming in general but I don't think the gap is as far as you make it seem.

**Comment by richardwales2820** [comment]
Well then I hope we can learn more together!

**Comment by jonpchin** [comment]
We are going to have to redo the front end. You used the GUI designer as a drag and drop which is fine but that means we have a lot of repeated code which can be shortened if we just use arrays and for loops. Also by using the GUI designer we would have to click each label and then manually copy and paste functions for all 225 labels which is unnecessary work. Instead we have to code the front end without using GUI designer by using for loops and arrays of labels/buttons. This way we can call a single cell on the Scrabble board by doing something such as ScrabbleBoard[14][7].setChar('A'). Instead of having to do label98.setText('A'). What I am trying to say is we need to implement a 2D array structure for the front end and using drag drop prevents of from doing that.

 Do you agree with me on this or do you know a way to remedy this situation?

**Comment by richardwales2820** [comment]
Sounds like a good idea. I look forward to seeing it. I'd like to see it in action to understand it

**Comment by jonpchin** [comment]
Before I make any code pushes here is what I am trying to do in pseudocode:

public static Label[,] frontEndBoard = new Label[15, 15];

            int i;
            int j;
            for (i = 0; i < 15; i++)
            {
                for (j = 0; j < 15; j++)
                {
                    frontEndBoard[i, j] = new Label();
                    frontEndBoard[i, j].Text = i + "," + j;
                    frontEndBoard[i, j].Size = new Size(50, 50);
                    frontEndBoard[i, j].Location = new Point(j * 50, i * 50);
                    
                }
            }

**Comment by jonpchin** [comment]
There is an issue with Visual Studio designer in that it makes it difficult to manually add code.  I am not allowed to edit the code in the designer area so I am trying to figure out where to place the front end logic.

**Comment by jonpchin** [comment]
Alright, I figured out where to add the frontend logic for the 2D array of labels/buttons I was talking about. I just pushed a working demo. We can always jump back to previous versions if it doesn't work out. That is the whole purpose of using source version control. See if you understand what I am trying to do.

We will add the color and bonus points on the tiles later on. Right now each tile just displays a multiplication matrix. But I wanted to show you how you can create a 2D array of buttons/labels using only 15 lines of code instead of 800 lines of code with the GUI designer.

**Comment by richardwales2820** [comment]
Looks awesome! I like this implementation better. And wow, you got a lot of the back end looking great. Where should we move from here?

**Comment by jonpchin** [comment]
We will proceed to work on getting the seven tiles drawn for the player and allowing the player to click the tiles and click the board to place the tile on the board. Also allowing player to finish turn, pass, or replace tiles. So there will be three buttons on the side that say Finish, Pass, or Replace Tiles. When a player presses finish the valid words will be scanned with the wordList.txt file using the backend board. The reason for using the backEnd board is because it will be more efficient to run high CPU intensive algorithms with a simple 2D char array whereas the frontEnd board is a little more advanced. When a player wants to undo a tile he placed on the board he just needs to click that tile and it will be placed in his hand. We also need to color/label the Scrabble board with the bonus points. This should be a simple task now with the 2D array setup. 

Once we finish all that we can proceed to making the computer play once its his turn. For easy level he will place a random letter. For hard level we will use Edit distance algorithm and the wordList to aide the computer.

I'll be working on it more tonight. Let me know which function or idea out of all the things I said you are interested in implementing. That way we both don't end up doing the same code by accident.

**Comment by richardwales2820** [comment]
For the finish button, I had an idea for checking the words. The function would check every placed tile and move as far left as possible, if there are tiles placed adjacent to it, and form words from left to right. And then also check the words formed at the top of each column above the placed letters. If the word is vertical, there would be one vertical word, and possibly several horizontal words formed, whereas a word in one row would have the opposite. I could work on this implementation tomorrow if you think it sounds reasonable.

**Comment by jonpchin** [comment]
Yes that sounds right. 

You could implement that algorithm using recursion(method calls) or iteration(for loops). For loops are more efficient then recursion when it comes to speed. Recursion usually has shorter/neater code but will be slower. So use for iteration(for loops) when doing the dictionary lookup. 

You can also do it a third method using queues/stacks which is more efficient then recursion . 
Also another thing we need to implement is have a point tracker to keep track of all the points the player scored when a valid word is found. Should be simple to implement.

**Comment by richardwales2820** [comment]
Alright cool, iteration it is. Sounds good!

**Comment by jonpchin** [comment]
The algorithm is called floodfiill. I used it in the minesweeper project for this organization, the code is still there. I used a Queue implementation as using for loops is actually very tricky. The queue implementation is theoretically as efficient as the for loop. If you need any help on it let me know.

**Comment by richardwales2820** [comment]
Oh I actually remember looking through that code last week and seeing that algorithm so you didnt overload the stack or something like that. Will do! I am currently getting Windows 10 from dreamspark to dual boot on my macbook so I can use visual studio when not on my desktop at home. I'd like to knock out these functions tomorrow between my classes. I'll let you know if everything goes terribly wrong!

**Comment by richardwales2820** [comment]
Alright, it's really late right now and I am off to sleep, but I added a quick function write-up I did to build words and verify them for each played tile. It has two lists as its parameters. They hold the x and y coordinates of each played tile. If you have any ideas to make this implementation better or see anything glaringly wrong with it, let me know! It looked good to me, but it hasn't been tested obviously, so it could be very bad! Look forward to working more tomorrow.

**Comment by jonpchin** [comment]
I took a look at your code. I like your implementation. You won't need to use floodfill algorithm. I forgot Scrabble only reads words that are from left to right and top to bottom. Plus I don't think most words will be longer then 10 chars so no need for flood fill. The way you implemented is good.

Just two suggestions. 

1. You don't have to pass an entire list of X and Y coordinates. Just pass in the starting x and y coordinates and then you can save those x and y coordinates to a local variable. Then just decrement those new variables as you can still fetch the original x and y coordinates. This way two list data structures don't have to be passed through a function every time the function is called but rather just two variables. In order to make this work what I'll do is when creating the the actioListeners for the frontEnd board I'll just set a private variable every time a player clicks and places a tile on the ScrabbleBoard, called Xcoordinate and yCoordinate using getter/setters and you will be able to fetch those x and y coordinates using getter/setters and pass them into your checkWords function you made. 

2. Also you won't have to reverse the string. The string reverse function has a little overhead. What you can do instead of word += tile, you can just do word = tile + word 
This is a just a small trick to add letters starting from the front instead of the back.

**Comment by jonpchin** [comment]
Also you'll have to check if there is a letter in all four directions. Even though a word is read from lead to right and top to bottom words, all that needs to be done is flip between appending words to the front and back. So the top and bottom string concatenation will have use both word += tile and word = tile + word, both ways read top to bottom but one fetches the word from a different direction.

Also one last tricky thing to consider is that there are two blank tiles which represent wild tiles. If you insert a blank into the string its going to fail with just the default lookup so we will have to have a if statement to check if a tile is blank and then make changes to lookup a word with a wild tile. The only way to do this I know is to do a linear brute force in O(n) or use the edit distance algorithm plus binary search which is more efficient but more difficult to implement.

**Comment by richardwales2820** [comment]
Good observations. I'll have to modify those then. I'd love to see the action listeners you're going to set up!

Regarding the wild tiles, does the user not select what letter the tile takes? I thought you could choose what letter the tile represents, but the score was still 0. Or does it instead act as a wildcard and the game selects the highest scoring word that can be formed with that wildcard?

**Comment by jonpchin** [comment]
Oh yes you are right about the player choosing the letter for the wild tile. In that case we will have to let the user enter something in for the letter he wants the tile to be.

**Comment by richardwales2820** [comment]
Oh and also, I'm not sure what naming conventions we are using, but I have been naming my functions with a capital letter using PascalCasing as I believe Microsoft outlined that as the language's design, but I don't want to make things confusing for you if all of my functions are named differently than yours.

You can take a look at this. I haven't been looking at it or following it religiously though. 
https://msdn.microsoft.com/en-us/library/ms229043(v=vs.110).aspx

**Comment by jonpchin** [comment]
Yes you bring up a good point. I been coding in Java for a while now so I am use to camelCase so I use that without even thinking. But we should stick with PascalCase as that is what Microsoft recommends for C#. For parameter names Microsoft says to use camelCase. 

I can handle either style. If you see incorrect style you can go ahead and change it. I'll do so as well as we continue to push code. It will take me a few days to fully adjust to PascalCase now that I am actually aware. And yes the coding style is important thing we should agree on. I read that webpage a while ago when learning the language thanks for bringing it up.

**Comment by jonpchin** [comment]
I changed everything to PascalCasing. Easy to do with mass refactoring. Also all chars for the letter of tiles are strings. The reason for this is it will make the word+= tile work properly. So what I had was 'A' now its "A". I added front end for the 7 player tiles. I'll be working on the actionListeners tonight.

**Comment by jonpchin** [comment]
I also uppercased all the words in the words.txt as we will only be using uppercase letters in Scrabble and the dictionary lookup will be case sensitive.

**Comment by jonpchin** [comment]
I just found out there is no such thing as a global variable in C#. All those global variables I made are now really global. I am now struggling to figure a way around this. I guess I am suppose to use getters and setters.

**Comment by richardwales2820** [comment]
If you want a variable to be "global" (not truly global in OOP I suppose) you could make a static class and have the property you want to be global as public static type. That should allow you to access it without instantiating anything. Or at least that's what I've picked up in the google-ing I did. Once you brought this up I became I really interested in what the heck I thought global variables in C# actually were!

**Comment by jonpchin** [comment]
I figured a way around. I just had to call the ClassName.MethodName().

**Comment by jonpchin** [comment]
Also I just uploaded the actionListeners. In C# they are called "Raising an Event". The Java version is actionListeners.

I just pushed some more code. Players can now click the Tile and place it on the board. They can also remove the Tile by clicking on the tile on the Scrabble board with the letter.

**Comment by jonpchin** [comment]
Oh there is a tiny bug where the tile doesn't get placed back into the hand if the player places multiple tiles on the board and then tries to undo them in a different order. I'll have to fix it tomorrow its getting late.

**Comment by jonpchin** [comment]
The bug is now fixed. Players can place tiles on the board and place them back in their hand by just clicking on the tiles on the board.

**Comment by richardwales2820** [comment]
Hmm, I am still getting that bug you described in some instances. And then for the word checker with the action listeners, how will the program know to remove the built words if the tile letters are removed from the board? I still feel like it would be better to make a list of points that are on the board, remove points that are removed by the user, and then when a "confirm" button is pushed, send out those coordinates to the word checker method that will then build all of those strings.

**Comment by jonpchin** [comment]
I did some more testing. The only bug I found was when I click multiple tiles in the players hand they would go missing. That bug is now fixed. I also added an a output console next to the board to display correct words that are formed and the points scored and the words the computer scored.

**Comment by jonpchin** [comment]
And yes you are right about needing a list for the X and Y coordinates of the tile to send to the checkWord function. There is two efficient ways we can do it. We can do it like you said and send both X and Y coordinates into two arrays.  Or we can send it into the function as one array using array pairs.
