### ISSUE TITLE
Scrabble Part 2

### ISSUE THREAD

**Issue by jonpchin** [hashSort/Scrabble#3]
The other thread was getting long so I figured we start a  new one.

I added the three buttons on the side and a rich textbox for output. We are using a pair<int, int > instead of two arraylists for the x and y coordinates.

I was proceeding to edit your checkWords function but realized the function is a lot more complicated then I previously thought. For example one small detail we overlooked: What happens if there is multiple valid substrings in a word? For example racecar has car, ace and racecar as valid words. We can have it where the game scores multiple words. Is that how Scrabble works?

 I'll help you work on the checkWords function in the next few days.

**Comment by richardwales2820** [comment]
Very good points. We'll have to revise some of the logic. Sorry I've gone MIA, I have an exam tomorrow and Wednesday so I've been studying. After Wednesday, I'll definitely be working on all of this! Thanks for managing everything so well with the project.

**Comment by jonpchin** [comment]
Yeah I had an exam today and another exam on Wednesday and a quiz on Wednesday. I get messages from group members saying they are busy too. We all are busy. I am just trying to sneak in some time to work on projects even though I should be studying. But studying 24/7 gets exhausting so I work on programming projects to relax.

**Comment by richardwales2820** [comment]
Heck yeah, programming is the most productive way of procrastinating! Awesome, look forward to working more :)

**Comment by jonpchin** [comment]
Players will now be prompted with an input box when they click a wild tile. Once a player enters a letter the letter will appear on the tile. I'll add error checking tomorrow so users can't edit digits or strings or special characters.

**Comment by jonpchin** [comment]
Also buttons are now highlighted in green when selected and disabled when placed on the board. Clicking the tile on the board enables the button again. Some other backend features were added to support the discard function in the future.

**Comment by jonpchin** [comment]
Visual Basic reference assembly was added to support the popup feature for the wild tile. .NET framework does not have a builtin popup feature so I had to pull from Visual Basic. In the future if we want to remove the Visual Basic assembly reference then we just have to manually make our own popup display.

**Comment by jonpchin** [comment]
For calculating the points we have two options. Option one, we can pre-compute the scores of each in the dictionary and store them with the word in the dictionary or option two, we can just calculate the word on the spot once the player forms a valid word.

The first way will take a lot of resources when the game loads since it has to calculate thousands of words and their scores but it gives a 0.1 second faster experience for the user when playing the game. However the second way is better since if you think about it a Scrabble game usually doesn't have more then ~100 words played out so it makes more sense to just calculate the score on spot.

My vote goes to option two.

**Comment by jonpchin** [comment]
Ignore the pre computing idea. I just remembered that their bonus tiles on the board. I just played Scrabble online for the first time at Pogo(website still stucks as they show 30 second annoying video ads that you can't close every 5 minutes. Also I now understand the rules of the game a bit better.

**Comment by jonpchin** [comment]
Rule#2 is special as it says "played" so that means even if the word is readable from left to right but played left to right then it won't be counted. I was confused when words I was playing weren't being counted. This rule 2 actually makes the algorithm checkWords function easier to code as we only need to check two directions. I thought we had to check four directions.

**Comment by jonpchin** [comment]
CheckWords function is mainly completed. CalculateScore function needs to be worked on. That function will return the points for the word. Right now dictionary lookup is working and the valid words are displayed in output box. We also need to work on placing the bonus point tiles on the ScrabbleBoard. We should now work on the point system and optimizing/cleaning up code.

**Comment by jonpchin** [comment]
I removed some unnecessary backend data structure and I removed Tile.cs as its not needed. Also CheckWords function and CalculateScore functions are completed. There is a slight bug as I can't figure a way to correctly check if all tiles are used. 

What I have implemented right now uses two hash table to keep track of placed Tiles and tiles that are used to make valid words. But there is an issue as subwords are also tracked by the hash tables so I have to make it so that only the longest word gets stored in the hash table. But the tricky part is the way we have it set up there is no way to tell which word is the longest until we build up all the words.

**Comment by jonpchin** [comment]
I am struggling to find a decent way to implement the CheckWords function. Surprisingly the function is very complicated. I came across several corner cases. I try to fix as many as I can but each time I fix a corner case another pops up. The CheckWords function now is rather long and complicated. Do you mind playing around with to find an efficient way to implement the function?

**Comment by jonpchin** [comment]
I think I found the issue. I need to check each letter I am adding if its a letter from this turn or previously played turn.

**Comment by richardwales2820** [comment]
Alright, what part of the project currently needs my attention? You've been working hard and have done so much! I appreciate all the work you've done with the club and this project.

**Comment by jonpchin** [comment]
I am currently in the process of rewriting CheckWords function. This function is the most complicated one in the entire project. Once this function is complete we should theoretically be able to use it for the computer to brute force possible words.

**Comment by jonpchin** [comment]
Still some bugs running around. You can go ahead and try to tackle the issues. 

1. Prevent duplicate words from being scored
2. Make sure a word is connected to the main island
3. Make sure all placed tiles on the board are used in valid words
4.Check words that use previously placed tiles

I had all four of these solved but not at once. I want to avoid writing extra data structures as there is already a lot of code in the CheckWords function but it seems like this is the only option as the string manipulation in this game is very advanced.

**Comment by jonpchin** [comment]
5. Make sure a valid word is at least part one placed tile.

Also the word.Substring(start, length) function gave me trouble with array index out of bounds for a long time as I thought it was start index and end index but it was start index and length which is very different.

**Comment by richardwales2820** [comment]
I noticed that when a letter was placed that had a duplicate in the player's hand, the tile you selected would stay highlighted if it was further to the right in your hand than the duplicate. I fixed this by saving the index of the selected button and using that to de-select and remove it, rather than searching the player's hand for the index.

**Comment by richardwales2820** [comment]
Although this doesn't support clicking multiple tiles at a time and placing them in one go, rather than doing one letter at a time. Might have to implement some sort of list that stores each individual letter's value and their index from the player hand

**Comment by jonpchin** [comment]
Yes I noticed that bug. I didn't fix its because it was only an aesthetic bug. And yes we may have to add another data structures to fix all the aesthetic bugs. 

For the CheckWords function if you want you can rewrite the entire function feel free. If you look in the github history you can see I tried many different strategies for string manipulation. Though the current CheckWords function I think is nearly fixed it just needs to fix the duplicate words.

**Comment by richardwales2820** [comment]
Yeah you got everything working very well! Just the aesthetic stuff and the duplicates. That function is huge and intimidating. I'll have to really go through it. Right now this aesthetic stuff is driving me crazy because I haven't been able to entirely fix it :P I'll keep chugging along for tonight.

**Comment by jonpchin** [comment]
I fixed the duplicate word problem. There is actually one more problem with CheckWords function that I have not fixed which is making sure a valid word is connected to the main island. Right now it only checks if its adjacent to the island which is not correct.

**Comment by jonpchin** [comment]
The 10 line deletion you made on line 197 you made gives a bug. I just added the code to my side locally to see if it appears again and the bug doesn't.

**Comment by jonpchin** [comment]
erm, line 215 I mean.

**Comment by richardwales2820** [comment]
I am in the process of fixing it at the moment using another list with some KeyValuePairs that tracks the hand index of each letter placed. Sorry about that. It is driving me crazy.

**Comment by richardwales2820** [comment]
Alright I got it! Right before I pushed I had to pull some merge from you, so I hope I didn't break anything with my push. I'm not sure if anything conflicted

**Comment by jonpchin** [comment]
There is a subtle bug in your code in which a letter gets placed on the board but the tile in the stays highlighted green and then the player can unclick the green tile in the hand and click it again and place an "extra" character onto the board.

**Comment by jonpchin** [comment]
The bug happens when clicking multiple tiles and placing multiple tiles.

**Comment by jonpchin** [comment]
By the way did you get strange injections into your code? I removed them but I was just curious why it happened. I had this happen to me before a while back. When there was a merge conflict Git would inject gibberish into code where edits were made.

**Comment by jonpchin** [comment]
I finished the CheckWords function. I am looking into setting up the computer play. I am considering using the backend board as its already setup and ready to go.
